# Generated by Django 3.0.6 on 2020-05-29 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آزمون')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد آزمون')),
                ('duration', models.DurationField(verbose_name='مدت زمان آزمون')),
                ('start_time', models.DateTimeField(verbose_name='تاریخ و ساعت شروع')),
                ('valid_submission_extensions', models.CharField(blank=True, max_length=50, verbose_name='فرمت\u200cهای مجاز فایل جواب')),
                ('question_file_path', models.FileField(upload_to='exam_files', verbose_name='فایل صورت آزمون')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد کلاس')),
                ('name', models.CharField(max_length=50, verbose_name='نام کلاس')),
            ],
            options={
                'verbose_name': 'کلاس درس',
                'verbose_name_plural': 'کلاس\u200cهای درس',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.SchoolClass', verbose_name='کلاس درس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانش\u200cآموز',
                'verbose_name_plural': 'دانش\u200cآموزان',
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='تاریخ و زمان ارسال')),
                ('answer_file', models.FileField(upload_to='submission_files', verbose_name='فایل پاسخ')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='آزمون')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'پاسخ ارسالی',
                'verbose_name_plural': 'پاسخ\u200cهای ارسالی',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.SchoolClass', verbose_name='کلاس درس'),
        ),
    ]
