# Generated by Django 3.0.6 on 2020-05-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='late_entry_minutes',
            field=models.DurationField(),
        ),
    ]
