# Generated by Django 3.0.6 on 2020-05-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20200528_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='duration_minutes',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='late_entry_minutes',
            new_name='late_entry',
        ),
    ]
