# Generated by Django 3.0.6 on 2020-05-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200528_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='late_entry',
        ),
    ]
