# Generated by Django 3.0.6 on 2020-05-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exam_late_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsubmission',
            old_name='answer_file_path',
            new_name='answer_file',
        ),
    ]
