# Generated by Django 3.0.6 on 2020-05-28 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_auto_20200528_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'آزمون', 'verbose_name_plural': 'آزمون\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='examsubmission',
            options={'verbose_name': 'پاسخ ارسالی', 'verbose_name_plural': 'پاسخ\u200cهای ارسالی'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'کلاس درس', 'verbose_name_plural': 'کلاس\u200cهای درس'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانش\u200cآموز', 'verbose_name_plural': 'دانش\u200cآموزان'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد آزمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(verbose_name='مدت زمان آزمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام آزمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_file_path',
            field=models.FileField(upload_to='exam_files', verbose_name='فایل صورت آزمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.SchoolClass', verbose_name='کلاس درس'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(verbose_name='تاریخ و ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='valid_submission_extensions',
            field=models.CharField(blank=True, max_length=50, verbose_name='فرمت\u200cهای مجاز فایل جواب'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='answer_file',
            field=models.FileField(upload_to='submission_files', verbose_name='فایل پاسخ'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Student', verbose_name='دانش\u200cآموز'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='time',
            field=models.DateTimeField(verbose_name='تاریخ و زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد کلاس'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام کلاس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.SchoolClass', verbose_name='کلاس درس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
